
import React, { useState } from 'react';
import { useLanguage } from '../context/LanguageContext.tsx';
// @ts-ignore
import { jsPDF } from 'jspdf';

const Certifications: React.FC = () => {
  const { t } = useLanguage();
  const [isDownloading, setIsDownloading] = useState(false);

  const downloadTechnicalPDF = async () => {
    setIsDownloading(true);
    
    try {
      const doc = new jsPDF();
      const primaryColor = '#0ea5e9'; // sky-500
      
      // Header
      doc.setFillColor(15, 23, 42); // slate-900
      doc.rect(0, 0, 210, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("MICROSEAL™", 20, 25);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("Advanced Surface Protection Technologies", 20, 32);
      
      doc.setFontSize(8);
      doc.text("CONFIDENTIAL TECHNICAL DOSSIER v2024.08", 140, 25);
      
      // Body Start
      let y = 55;
      
      const drawSectionHeader = (title: string) => {
        doc.setFillColor(241, 245, 249); // slate-100
        doc.rect(20, y - 5, 170, 8, 'F');
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text(title.toUpperCase(), 25, y);
        y += 12;
      };

      const drawDataRow = (label: string, value: string) => {
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(71, 85, 105); // slate-600
        doc.text(label, 25, y);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(15, 23, 42);
        doc.text(value, 85, y);
        y += 7;
      };

      // Section 1: Product Identification
      drawSectionHeader(t("Identifikasi Produk", "Product Identification"));
      drawDataRow(t("Nama Produk", "Product Name"), "Microseal™ Nano-Bond Pro Gen-3");
      drawDataRow(t("Basis Teknologi", "Technology Base"), "Silane-Siloxane Hybrid / Covalent Nano-Matrix");
      drawDataRow(t("Carrier Liquid", "Carrier Liquid"), t("Berbasis Air (Ramah Lingkungan)", "Water-based (Eco-Friendly)"));
      drawDataRow(t("Penampilan", "Appearance"), t("Cairan Bening Transparan", "Clear Transparent Liquid"));
      
      y += 10;
      
      // Section 2: Physical Properties
      drawSectionHeader(t("Sifat Fisika & Kimia", "Physical & Chemical Properties"));
      drawDataRow(t("Ukuran Partikel", "Particle Size"), "< 5 Nanometers (Atomic Scale)");
      drawDataRow(t("Kandungan VOC", "VOC Content"), "0.0 g/L (Zero VOC)");
      drawDataRow(t("Titik Nyala", "Flash Point"), t("Tidak Terbakar", "Non-flammable"));
      drawDataRow(t("Massa Jenis", "Specific Gravity"), "1.02 @ 25°C");
      drawDataRow("pH Level", "7.5 (Neutral)");
      drawDataRow(t("Waktu Kering", "Drying Time"), "30 - 60 Minutes (Touch Dry)");
      drawDataRow(t("Aktivasi Penuh", "Full Cure"), "24 Hours");

      y += 10;

      // Section 3: Performance Standards
      drawSectionHeader(t("Standar Performa (ASTM)", "Performance Standards (ASTM)"));
      drawDataRow("ASTM G154 (UV)", t("Lulus (2000 Jam Tanpa Degradasi)", "Pass (2000 Hours No Degradation)"));
      drawDataRow("ASTM D4060 (Abrasi)", t("Ketahanan Tinggi (CS-17 Wheels)", "High Resistance (CS-17 Wheels)"));
      drawDataRow("ASTM D3359 (Adhesi)", t("Klasifikasi 5B (Sangat Kuat)", "Classification 5B (Superior)"));
      drawDataRow("ASTM E96 (Breathability)", t("98% Permeabilitas Uap Air", "98% Water Vapor Permeability"));
      
      y += 10;

      // Section 4: Application Scope
      drawSectionHeader(t("Cakupan Aplikasi & Estimasi", "Application Scope & Coverage"));
      drawDataRow(t("Beton / Semen", "Concrete / Cement"), "8 - 12 m²/Liter");
      drawDataRow(t("Batu Alam / Bata", "Natural Stone / Brick"), "6 - 10 m²/Liter");
      drawDataRow(t("Kayu Berpori", "Porous Wood"), "10 - 14 m²/Liter");

      // Footer
      doc.setDrawColor(226, 232, 240);
      doc.line(20, 275, 190, 275);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text("Generated by Microseal Intelligent Engine • © 2024 Microseal Technologies Inc.", 105, 282, { align: "center" });
      doc.text("ISO 9001:2015 Certified Production Facility", 105, 287, { align: "center" });

      // Save PDF
      doc.save('Microseal_Technical_Data_Sheet_Full_2024.pdf');
      
    } catch (error) {
      console.error("PDF Generation Error:", error);
    } finally {
      setIsDownloading(false);
    }
  };

  const certs = [
    {
      title: 'ISO 9001:2015',
      org: t('Manajemen Mutu', 'Quality Management'),
      desc: t('Sertifikasi standar internasional untuk sistem manajemen mutu produksi nano-chemical.', 'International standard certification for nano-chemical production quality management systems.'),
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
        </svg>
      )
    },
    {
      title: 'ASTM G154',
      org: t('Resistensi UV', 'UV Resistance'),
      desc: t('Teruji secara laboratorium terhadap paparan sinar UV ekstrem tanpa degradasi molekuler.', 'Laboratory tested against extreme UV exposure without molecular degradation.'),
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364-6.364l-.707.707M6.343 17.657l-.707.707m12.728 0l-.707-.707M6.343 6.343l-.707-.707M12 8a4 4 0 100 8 4 4 0 000-8z" />
        </svg>
      )
    },
    {
      title: t('Kepatuhan REACH', 'REACH Compliance'),
      org: t('Label Keamanan Ekologis', 'Eco-Safety Label'),
      desc: t('Memenuhi standar regulasi Uni Eropa untuk keamanan bahan kimia terhadap kesehatan dan lingkungan.', 'Meets EU regulatory standards for chemical safety regarding health and the environment.'),
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
      )
    },
    {
      title: 'ASTM D4060',
      org: t('Resistensi Abrasi', 'Abrasion Resistance'),
      desc: t('Skor ketahanan abrasi tinggi (Taber Abraser), ideal untuk area dengan lalu lintas beban berat.', 'High abrasion resistance score (Taber Abraser), ideal for heavy traffic areas.'),
      icon: (
        <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
      )
    }
  ];

  return (
    <section id="certifications" className="py-24 bg-slate-900 overflow-hidden relative">
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-sky-500/5 blur-[120px] rounded-full translate-x-1/2 -translate-y-1/2"></div>
      
      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-8">
          <div>
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-4 tracking-tight">
              {t('Kepatuhan & Standar', 'Compliance & Standards')} <span className="text-sky-500">{t('Global', 'Global')}</span>
            </h2>
            <p className="text-slate-400 text-lg max-w-xl">
              {t('Produk kami melalui pengujian ketat di laboratorium independen untuk memastikan kualitas teknis tertinggi.', 'Our products undergo rigorous testing in independent laboratories to ensure the highest technical quality.')}
            </p>
          </div>
          <div className="hidden md:block">
             <div className="flex -space-x-4">
               {[1,2,3,4].map(i => (
                 <div key={i} className="w-12 h-12 rounded-full border-2 border-white bg-slate-100 flex items-center justify-center text-[10px] font-bold text-slate-500 shadow-xl">LAB</div>
               ))}
             </div>
          </div>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {certs.map((cert, i) => (
            <div key={i} className="group p-8 bg-slate-950 border border-white/5 rounded-[32px] hover:border-sky-500/30 transition-all duration-500 hover:-translate-y-2 shadow-sm">
              <div className="w-14 h-14 rounded-2xl bg-sky-500/10 border border-sky-500/20 flex items-center justify-center text-sky-500 mb-8 group-hover:bg-sky-500 group-hover:text-slate-950 transition-colors">
                {cert.icon}
              </div>
              <div className="text-[10px] text-sky-400 font-black uppercase tracking-[0.2em] mb-2">{cert.org}</div>
              <h4 className="text-xl font-bold text-white mb-4">{cert.title}</h4>
              <p className="text-sm text-slate-400 leading-relaxed">{cert.desc}</p>
            </div>
          ))}
        </div>

        <div className="mt-16 p-8 md:p-12 rounded-[40px] bg-slate-950 border border-white/5 flex flex-col md:flex-row items-center gap-12 relative overflow-hidden group shadow-lg">
           <div className="absolute inset-0 bg-sky-500/5 opacity-0 group-hover:opacity-100 transition-opacity"></div>
           <div className="flex-1 relative z-10">
              <div className="inline-block px-3 py-1 bg-emerald-500/10 text-emerald-500 text-[10px] font-black uppercase tracking-widest rounded mb-4 border border-emerald-500/20">{t('Verifikasi Aktif', 'Verification Active')}</div>
              <h3 className="text-2xl md:text-3xl font-bold text-white mb-4">{t('Minta Dossier Teknis', 'Request Technical Dossier')}</h3>
              <p className="text-slate-400 text-sm md:text-base leading-relaxed mb-8 max-w-xl">
                {t('Kami menyediakan laporan hasil uji laboratorium lengkap (Full Lab Reports) untuk spesifikasi proyek skala besar. Dokumen ini mencakup analisis molekuler dan uji ketahanan jangka panjang.', 'We provide complete laboratory test reports (Full Lab Reports) for large-scale project specifications. This document includes molecular analysis and long-term durability tests.')}
              </p>
              <button 
                onClick={downloadTechnicalPDF}
                disabled={isDownloading}
                className={`px-8 py-4 bg-sky-500 hover:bg-sky-400 text-slate-950 text-sm font-black rounded-xl transition-all border border-transparent flex items-center gap-3 shadow-[0_0_30px_rgba(14,165,233,0.3)] disabled:opacity-50 disabled:cursor-not-allowed`}
              >
                {isDownloading ? (
                  <>
                    <div className="w-4 h-4 border-2 border-slate-950 border-t-transparent rounded-full animate-spin"></div>
                    {t('Menyusun PDF...', 'Generating PDF...')}
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
                    {t('Unduh Bundel Sertifikasi (.PDF)', 'Download Certification Bundle (.PDF)')}
                  </>
                )}
              </button>
           </div>
           <div className="w-full md:w-1/3 aspect-[4/3] bg-slate-900 rounded-3xl border border-white/10 flex items-center justify-center relative overflow-hidden shadow-2xl">
              <div className="absolute inset-0 opacity-20 bg-[url('https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&q=80&w=800')] bg-cover transition-transform duration-700 group-hover:scale-110"></div>
              <div className="relative z-10 text-center px-6">
                <div className="text-5xl mb-4 filter drop-shadow-2xl">📄</div>
                <div className="text-[10px] font-black text-white uppercase tracking-widest bg-slate-950/80 px-4 py-2 rounded-full backdrop-blur-md border border-white/10">
                  Certified Batch 2024.08
                </div>
              </div>
           </div>
        </div>
      </div>
    </section>
  );
};

export default Certifications;
